# Generated by Django 4.0.6 on 2022-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('post_code', models.IntegerField(max_length=7)),
            ],
        ),
    ]
