# Generated by Django 4.0.6 on 2022-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='post_code',
            field=models.IntegerField(),
        ),
    ]
